language: go
sudo: false
go:
- 1.10.x
before_install:
- go get github.com/mattn/goveralls
- go get github.com/axw/gocov/gocov
- go get golang.org/x/tools/cmd/cover
os:
- linux
script:
- go build -race
- go test -v ./...  -coverprofile=cover.out
- go test -run=bench -cpuprofile=cpu.pprof -memprofile=mem.pprof -benchmem -bench ^Benchmark
after_success:
  - bash <(curl -s https://codecov.io/bash)
